apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifest.yaml
  - nodeport.yaml
  - repo-server-role.yaml
  - repo-server-rolebinding.yaml
  - argocd-cm-plugin.yaml
patchesStrategicMerge:
  - repo-server-deployment-patch.yaml

labels:
  - pairs:
      self-managed-argocd: "true"





